### ISSUE TITLE
Supybot - No longer pulls correct information

### ISSUE THREAD

**Issue by nazunalika** [buckket/erica#4]
The supybot plugin here appears to no longer work. I'm assuming it's due to google's API change. 

ERROR 2015-05-11T09:51:20 Uncaught exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/supybot/log.py", line 351, in m
    return f(self, _args, *_kwargs)
  File "/usr/lib/python2.7/site-packages/supybot/irclib.py", line 132, in **call**
    method(irc, msg)
  File "/home/sares/supy/plugins/Supytube/plugin.py", line 61, in doPrivmsg
    likes = float(data['entry']["yt$rating"]['numLikes'])
KeyError: 'yt$rating'
ERROR 2015-05-11T09:51:20 Exception id: 0xf6c70

**Comment by buckket** [comment]
Yeah, that’s right. Due to Google’s API change things got a little bit more complicated.
I will fix it as soon as I've got the time for it.

**Comment by buckket** [comment]
Fixed it in 238cfb398bf14d0f2cee1474d08a5b415268fa85, also thanks to @gaurdro for providing a starting point. :+1:
